version: '3'
services:
  p-test-mongo:
    image: mongo
    container_name: p-test-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db' #数据持久化，在主机上的执行文件夹中创建.docker-volumes目录
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27016:27017
    env_file:
      - .env
  p-test-redis:
    image: redis
    container_name: p-test-redis
    command: >  #执行此命令之前的命令
      redis-server  /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - '.docker-volumes/redis/data:/data' #数据持久化，在主机上的执行文件夹中vvvvvvvvcfffffffff创建.docker-volumes目录
    ports:
      - 6378:6379
    env_file:
      - .env
  p-test-backend:
    image: crpi-yacuoj1e11qkasck.cn-beijing.personal.cr.aliyuncs.com/jiaozenghui/p-test:1.0.0
    container_name: p-test-backend
    ports:
      - 7006:7006
    env_file:
      - .env